Exam12/Controllers/GalleryController.cs
using System.IO;
using System.Threading.Tasks;
using Exam12.Models;
using Exam12.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Exam12.Controllers
{
    public class GalleryController : Controller
    {
        private readonly ApplicationContext _applicationContext;
        private readonly UserManager<User> _userManager;

        public GalleryController(ApplicationContext applicationContext, UserManager<User> userManager)
        {
            _applicationContext = applicationContext;
            _userManager = userManager;
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(AddGalleryImageViewModel model)
        {
            var user = _userManager.GetUserAsync(User);
            using var stream = new FileStream(model.GetFilePath(), FileMode.Create);
            model.Image.CopyTo(stream);
            var galleryImage = new GalleryImage
            {
                ImagePath = model.GetImagePath(),
                PlaceId = model.PlaceId,
                UserId = user.Result.Id
            };
            await _applicationContext.AddAsync(galleryImage);
            await _applicationContext.SaveChangesAsync();
            return RedirectToAction("Index", "Place", new{placeId = model.PlaceId});
        }
    }
}

Exam12/Controllers/PlaceController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Exam12.Models;
using Exam12.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Exam12.Controllers
{
    public class PlaceController : Controller
    {
        private readonly ApplicationContext _applicationContext;

        public PlaceController(ApplicationContext applicationContext)
        {
            _applicationContext = applicationContext;
        }

        [HttpGet]
        public IActionResult Index(string placeId)
        {
            return View(_applicationContext.Places.Find(placeId));
        }


        [HttpGet]
        [Authorize]
        public IActionResult AddPlace() => View();

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPlace(AddPlaceViewModel model)
        {
            if (!ModelState.IsValid) return View();
            using var stream = new FileStream(model.GetFilePath(), FileMode.Create);
            model.MainImage.CopyTo(stream);
            
            var place = model.GetPlace();
            place.MainImagePath = model.GetAvatarImagePath();

            await _applicationContext.AddAsync(place);
            await _applicationContext.SaveChangesAsync();
            return RedirectToAction("Index", "Home");   
        }
        
        public IActionResult CheckTitle(AddPlaceViewModel model)
        {
            model.Title = model.Title.Trim(); 
            return Ok(!_applicationContext.Places.Any(p => 
                string.Equals(p.Title, model.Title, StringComparison.CurrentCultureIgnoreCase)));
        
        }
        
        public IActionResult LiveSearchAjaxResult(string keyWord)
        {
            if (!string.IsNullOrEmpty(keyWord))
            {
                keyWord = keyWord.ToLower().Trim();
            }

            var places = _applicationContext.Places.Where(u => u.Description.ToLower().Contains(keyWord)
                                                      || u.Title.ToLower().Contains(keyWord)).ToList();
            return PartialView("PartialViews/PlaceLiveSearchResult", places);
        }
    }
}

Exam12/Controllers/ReviewController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Exam12.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Exam12.Controllers
{
    public class ReviewController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ApplicationContext _applicationContext;

        public ReviewController(ApplicationContext applicationContext, UserManager<User> userManager)
        {
            _applicationContext = applicationContext;
            _userManager = userManager;
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Add(string placeId, string message, double rating)
        {
            var user = _userManager.GetUserAsync(User);
            var review = new Review()
            {
                Message = message,
                DateTime = DateTime.Now,
                PlaceId = placeId,
                UserId = user.Result.Id,
                Rating = rating
            };
            await _applicationContext.Reviews.AddAsync(review);
            await _applicationContext.SaveChangesAsync();
            return Ok();
        }

        public IActionResult GiveReviews(string placeId )
        {
            var reviews = _applicationContext.Reviews.Where(r => r.PlaceId == placeId);
            return Json(reviews);
        }
        
        
    }
}

Exam12/Views/Shared/PartialViews/AddGalleryImagePartial.cshtml
@model Exam12.ViewModels.AddGalleryImageViewModel
<form method="POST" asp-controller="Gallery" asp-action="Add" class="form-horizontal" enctype="multipart/form-data">
     <div asp-validation-summary="ModelOnly"></div>
    <div class="form-group ml-3">
        <input type="file" asp-for="Image" class="form-control-file">
        <span asp-validation-for="Image"></span>
    </div>
    <input type="hidden" asp-for="PlaceId" value="@Model.PlaceId">
    <input type="submit" value="Add gallery image" class="btn btn-success ml-3"/>
</form>        
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

Exam12/Views/Shared/PartialViews/PlaceLiveSearchResult.cshtml
@model List<Exam12.Models.Place>
<div id="searchresults" class="d-flex flex-column w-100">
    @if (@Model.Count > 0)
    {
        foreach (var place in Model)
        {
            <div class="py-2">
                <img width="50" height="50" class="rounded-circle" src="~/@place.MainImagePath" alt="image"/>
                <a class="col-lg-4 text-center text-dark" asp-action="Index" asp-controller="Place"
                   asp-route-placeId="@place.Id">
                    @place.Title</a>
            </div>
        }
    }
</div>

Exam12/Views/Shared/PartialViews/ReviewPartial.cshtml
@using Exam12.Models
@model Exam12.Models.Review
@inject ApplicationContext Context
<h2 class="mt-5 mb-5">Reviews</h2>
<style>
    .num {
      display: none;
    }
    .paginator {
      line-height: 150%;
    }
    .paginator > span {
      display: inline-block;
      margin-right: 10px;
      cursor: pointer;
    }
    .paginator_active {
      color: red;
    }
</style>
@{
    var count = Context.Reviews.Count(a => a.PlaceId == Model.PlaceId);
    var i = 1;
    var reviews = Context.Reviews.Where(r => r.PlaceId == @Model.PlaceId).ToList();
    foreach (var review in reviews.OrderBy(r => r.DateTime))
    {
        <div class="message num" data-num=@i>
            <p>On @review.DateTime, <span class="font-weight-bold">@review.User.UserName</span> said: </p>
            <p>@review.Message</p>
        </div>
        i++;
    }
    <div id="light-pagination" class="pagination"></div>
    <span id="app"></span>
}
<div class="form-group col-lg-12">
    @{
        if (User.Identity.IsAuthenticated)
        {
            <form method="post">
                <div asp-validation-summary="ModelOnly"></div>
                <textarea  class="form-control" id="postText-@Model.PlaceId"></textarea>
                <span asp-validation-for="Message"></span>
                <div class="form-group ">
                    <select class="form-control col-lg-1" id="rate">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4" selected>4</option>
                        <option value="5">5</option>
                    </select>
                </div>
                <button class="btn btn-outline-dark" type="button"
                        onclick="addReview('@Model.PlaceId', '@User.Identity.Name')">
                    Add Review
                </button>
            </form>
            
        }
    }
</div>
<div class="paginator" onclick="pagination(event)"></div>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script> 
function addReview(placeId, userName) {
    var appendString =  '<div class="message" data-num=@i>\n'+
                        '<p>On' + '@DateTime.Now' + ', <span class="font-weight-bold">'+ userName +'</span> said: </p>\n'+
                        '<p>' +  $('#postText-' + placeId).val() + '</p>\n'+
                        '</div>';

    $.ajax({
            url: '@Url.Action("Add", "Review")',
            method: 'POST',
            data: {
                'rating':$('#rate').val(),
                'placeId': placeId,
                'message': $('#postText-' + placeId).val()
            },
            success: function () {
                $('#app').
                append(appendString);
                $('#postText-' + placeId).val(null);
                $('body, html').scrollTop($(document).height());
            }
        }
    );
}
var count = @count;
var cnt = 5;
var cnt_page = Math.ceil(count / cnt);


var paginator = document.querySelector(".paginator");
var page = "";
for (var i = 0; i < cnt_page; i++) {
    page += "<span data-page=" + i * cnt + "  id=\"page" + (i + 1) + "\">" + (i + 1) + "</span>";
}
paginator.innerHTML = page;


var div_num = document.querySelectorAll(".num");
for (var i = 0; i < div_num.length; i++) {
    if (i < cnt) {
        div_num[i].style.display = "block";
    }
}

var main_page = document.getElementById("page1");
main_page.classList.add("paginator_active");


function pagination(event) {
    var e = event || window.event;
    var target = e.target;
    var id = target.id;

    if (target.tagName.toLowerCase() != "span") return;

    var num_ = id.substr(4);
    var data_page = +target.dataset.page;
    main_page.classList.remove("paginator_active");
    main_page = document.getElementById(id);
    main_page.classList.add("paginator_active");

    var j = 0;
    for (var i = 0; i < div_num.length; i++) {
        var data_num = div_num[i].dataset.num;
        if (data_num <= data_page || data_num >= data_page)
            div_num[i].style.display = "none";

    }
    for (var i = data_page; i < div_num.length; i++) {
        if (j >= cnt) break;
        div_num[i].style.display = "block";
        j++;
    }
}
</script>