Exam12/Controllers/PlaceController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Exam12.Models;
using Exam12.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Exam12.Controllers
{
    public class PlaceController : Controller
    {
        private readonly ApplicationContext _applicationContext;

        public PlaceController(ApplicationContext applicationContext)
        {
            _applicationContext = applicationContext;
        }

        [HttpGet]
        public IActionResult Index(string placeId)
        {
            return View(_applicationContext.Places.Find(placeId));
        }


        [HttpGet]
        [Authorize]
        public IActionResult AddPlace() => View();

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPlace(AddPlaceViewModel model)
        {
            if (!ModelState.IsValid) return View();
            using var stream = new FileStream(model.GetFilePath(), FileMode.Create);
            model.MainImage.CopyTo(stream);
            
            var place = model.GetPlace();
            place.MainImagePath = model.GetAvatarImagePath();

            await _applicationContext.AddAsync(place);
            await _applicationContext.SaveChangesAsync();
            return RedirectToAction("Index", "Home");   
        }
        
        public IActionResult CheckTitle(AddPlaceViewModel model)
        {
            model.Title = model.Title.Trim(); 
            return Ok(!_applicationContext.Places.Any(p => 
                string.Equals(p.Title, model.Title, StringComparison.CurrentCultureIgnoreCase)));
        
        }
        
        public IActionResult LiveSearchAjaxResult(string keyWord)
        {
            if (!string.IsNullOrEmpty(keyWord))
            {
                keyWord = keyWord.ToLower().Trim();
            }

            var places = _applicationContext.Places.Where(u => u.Description.ToLower().Contains(keyWord)
                                                      || u.Title.ToLower().Contains(keyWord)).ToList();
            return PartialView("PartialViews/PlaceLiveSearchResult", places);
        }
    }
}

Exam12/Controllers/UserController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Exam12.Models;
using Exam12.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SignInResult = Microsoft.AspNetCore.Identity.SignInResult;

namespace Exam12.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public UserController(UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Registration() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Registration(RegistrationViewModel model)
        {
            if (!ModelState.IsValid) return View(model);
            using var stream = new FileStream(model.GetFilePath(), FileMode.Create);
            model.Avatar.CopyTo(stream);

            var user = model.GetUser();
            user.AvatarImagePath = model.GetAvatarImagePath();

            var result = await _userManager.CreateAsync(user, model.Password);

            if (result.Succeeded)
            {
                await _signInManager.SignInAsync(user, false);
                return RedirectToAction("Index", "Home");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

            return View(model);
        }

        [HttpGet]
        
        public IActionResult LogIn(string returnUrl = null)
        {
            return View(new LogInViewModel {ReturnUrl = returnUrl});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogIn(LogInViewModel model)
        {
            var result = SignInResult.Failed;
            if (!ModelState.IsValid) return View(model);
            var user = await _userManager.FindByNameAsync(model.UserName);
            if (user != null)
            {
                result = await _signInManager.PasswordSignInAsync(user,
                    model.Password, model.RememberMe, false);
            }

            if (result.Succeeded)
            {
                if (!string.IsNullOrEmpty(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl))
                {
                    return Redirect(model.ReturnUrl);
                }

                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError("", "Неправильный логин и (или) пароль");
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        
        public IActionResult CheckName(RegistrationViewModel model)
        {
            var user = model.GetUser();
            model.UserName = model.UserName.Trim();
            bool isTrue;
            if (string.IsNullOrEmpty(user.Id))
                isTrue = _userManager.Users.Any(b => string.Equals(b.UserName.Trim(), model.UserName,
                    StringComparison.CurrentCultureIgnoreCase));
            else
            {
                if (_userManager.Users.Any(b => string.Equals(b.UserName.Trim(), model.UserName,
                                                    StringComparison.CurrentCultureIgnoreCase) && b.Id == user.Id))
                {
                    return Ok(true);
                }

                return Ok(!_userManager.Users.Any(b => string.Equals(b.UserName.Trim(), model.UserName,
                    StringComparison.CurrentCultureIgnoreCase)));
            }
            return Ok(isTrue);
        }
        
        public IActionResult CheckEmail(RegistrationViewModel model)
        {
            model.Email = model.Email.Trim();
            return Ok(!_userManager.Users.Any(u => u.Email == model.Email));
        }
    }
}

Exam12/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Exam_12</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/js/v2.3.2/jquery.rateyo.css">
    <link rel="stylesheet" href="css/chocolate.css">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Exam_12</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="nav navbar-nav navbar-right d-flex">
                    <li class="nav-item position-relative mr-5">
                        <input class="form-control"
                               oninput="liveSearch()"
                               type="text"
                               name="searchKey"
                               id="search"/>
                        <div id="results" class="col-md-12 position-absolute d-inline-flex flex-column w-100  bg-light"
                             style="z-index: 999999">
                        </div>
                         <div id="results1 col-md-12 position-absolute d-inline-flex flex-column" ></div>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <form asp-action="LogOut" asp-controller="User">
                            <button class="btn btn-dark" asp-area="" asp-controller="User"
                                    asp-action="LogOut">
                                Logout
                            </button>
                        </form>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Place" asp-action="AddPlace">Add new place</a>
                        </li>
                        <li class="ml-2">@User.Identity.Name</li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Registration">Registration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="LogIn">Login</a>
                        </li>
                    }

                </ul>
                <input class="btn btn-outline-primary dropdown-toggle" type="button" id="submit" value="Search"/>
                   
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2019 - Exam_12
    </div>
</footer>
<script src="~/js/v2.3.2/jquery.min.js"></script>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/js/v2.3.2/jquery.rateyo.min.js"></script>
<script src="js/chocolate.js"></script>
@RenderSection("Scripts", required: false)
<script>
    function liveSearch(){
        var searchKey = $('#search').val();
        searchKey = encodeURIComponent(searchKey);
        $('#results').load('@Url.Action("LiveSearchAjaxResult", "Place")?keyWord=' + searchKey);
    }
    function search() {
        var searchKey = $('#search').val();
        searchKey = encodeURIComponent(searchKey);
        $('#results1').load('@Url.Action("LiveSearchAjaxResult", "Place")?keyWord=' + searchKey);
    }
</script>
</body>
</html>